### ISSUE TITLE
@baseContext does not work

### ISSUE THREAD

**Issue by daniellansun** [sharwell/antlr4#24]
Hi Sam,

   I find `@baseContext` does not work as expected: LambdaParametersContext does not extend StandardLambdaParametersContext. Could you have a look? Thanks in advance!

``` antlr
lambdaParameters
@baseContext{ standardLambdaParameters }
    :   LPAREN formalParameterList? RPAREN
    ;

standardLambdaParameters
    :   LPAREN formalParameterList? RPAREN
    |   variableDeclaratorId
    ;
```

``` java
    public static class LambdaParametersContext extends GroovyParserRuleContext {
    ...
    }
```

**Comment by sharwell** [comment]
It looks like this should actually work like the following:

``` antlr
lambdaParameters
options { baseContext = standardLambdaParameters; }
  : LPAREN formalParameterList? RPAREN
  ;
```

📝 Note that when using the `baseContext` option, `LambdaParametersContext` will not exist at all. Both `lambdaParameters()` and `standardLambdaParameters()` will return `StandardLambdaParametersContext`.

**Comment by daniellansun** [comment]
Wow! It works. Thanks a lot, Sam :-)
